export const products = [
  // Guttering
  {
    id: 'lysaght-downpipes-round',
    title: 'Lysaght Downpipes Round',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/DownPipesRound/DownPipesRound_1.png',
    ],
    highlightDetails: {
      features: ['Manufactured from premium COLORBOND® steel or ZINCALUME® steel, ensuring longevity and resistance to Australia diverse climatic conditions.', 'Available in various sizes to accommodate different building requirements, with the 90mm and 100mm round profile being a common choice.', 'A full range of accessories is available, including brackets/astragals, pops/nozzles, offsets, elbows, and shoes, facilitating seamless integration into any drainage system.'],
      productInfo: 'LYSAGHT® offersa a range of high-quality downpipes crafted from durable COLORBOND® steel and ZINCALUME® steel. Among these, the round profile downpipes are particularly notable for their efficiency and aesthetic appeal.',
      specifications: {
        'Profile style': 'Round',
        'Nominal Width': '90mm and 100mm',
        'suitable for': 'Guttering'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/DownPipes_accessories.pdf"
  },
  {
    id: 'lysaght-half-round-150',
    title: 'Lysaght Half Round 150',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/HalfRound150/HalfRound150_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/HalfRound150/HalfRound150_2.jpg',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours', 'Curved base reduces ongoing maintenance requirements due to self-cleaning capability'],
      productInfo:
        'A modern gutter shape with a high rainfall carrying capacity, and a curved base for improved self-cleaning and minimal build-up of water and dirt. Readily used for both steel and tile roofs, HALF ROUND gutter is ideal for contemporary homes in addition to commercial and industrial buildings where a high rainfall carrying capacity is required.',
      specifications: {
        'Profile style': 'Round',
        'Nominal Front Height': '97mm',
        'Nominal Width': '150mm',
        'Nominal Back Height': '73mm',
        'Slotting': 'Slotted or unslotted',
        'suitable for': 'guttering.'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/HalfRound_accessories.pdf"
  },
  // Repeat for other products

  {
    id: 'lysaght-flat-back-150',
    title: 'Lysaght Flat Back 150',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/FlatBack150/FlatBack150_1.png',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours', 'Curved base reduces ongoing maintenance requirements due to self-cleaning capability'],
      productInfo:
        'A modern gutter shape with a high rainfall carrying capacity, a curved base for improved self-cleaning and minimal build-up of water and dirt. Readily used for both steel and tile roofs, FLAT BACK gutter is ideal for contemporary homes and where a high rainfall carrying capacity is required.',
      specifications: {
        'Profile style': 'Round',
        'Nominal Front Height': '97mm',
        'Nominal Width': '136mm',
        'Nominal Back Height': '74mm',
        'Slotting': 'Slotted or unslotted',
        'suitable for': 'guttering.'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/FlatBackGutter_accessories.pdf"
  },
  {
    id: 'lysaght-downpipes-square',
    title: 'Lysaght Downpipes Square',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/DownPipesSquare/DownPipesSquare_100X50.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/DownPipesSquare/DownPipesSquare_100X75.png',
    ],
    highlightDetails: {
      features: ['Manufactured from premium COLORBOND® steel or ZINCALUME® steel, ensuring longevity and resistance to Australia diverse climatic conditions.', 'Available in various dimension to accommodate different building requirements, with the 100mmx50mm and 100mmx50mm square profile being a common choice.', 'A full range of accessories is available, including brackets/astragals, pops/nozzles, offsets, elbows, and shoes, facilitating seamless integration into any drainage system.'],
      productInfo:
        'LYSAGHT® offers a range of high-quality downpipes crafted from durable COLORBOND® steel and ZINCALUME® steel. Among these, the square profile downpipes are particularly notable for their clean lines and robust design, making them ideal for modern and industrial architectural styles.',
      specifications: {
        'Profile style': 'Square',
        'Dimensions': '100mm x 50mm OR 100mm x 75mm',
        'suitable for': 'Guttering'
      },
    },
    colors: [
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/DownPipesSquare_accessories.pdf"
  },
  {
    id: 'lysaght-quad',
    title: 'Lysaght Quad',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Quad/Quad_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Quad/Quad_2.png',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours'],
      productInfo:
        'A classic gutter shape suited to both new homes and replacement of existing gutters. Readily used for both steel and tile roofs, QUAD gutter is an allrounder suitable for a broad range of architectural styles and applications on houses, patios, carports & sheds.',
      specifications: {
        'Profile style': 'Quad/D',
        'Nominal Front Height': '19mm for Hi-Front and 70mm for Lo-Front',
        'Nominal Width': '115mm',
        'Nominal Back Height': '65mm',
        'Slotting': 'Slotted or unslotted',
        'suitable for': 'guttering.'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Quad_accessories.pdf"
  },
  {
    id: 'lysaght-novaline',
    title: 'Lysaght Novaline',
    type: 'fascia',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/NovaLine/NovaLine_1.png',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours'],
      productInfo:
        'An easy to use and fast to install steel fascia compatible with an extensive range of LYSAGHT® Guttering profiles, NOVALINE® Fascia is complemented by a range of steel accessories to deliver a complete fascia system for residential properties.',
      specifications: {
        'Nominal  Height': '185mm',
        'Nominal Top Width': '18mm',
        'Nominal Bottom Width': '35mm',
        'suitable for': 'Fascia'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Novaline_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure"
  },
  {
    id: 'lysaght-novalinecover',
    title: 'Lysaght Novaline Cover',
    type: 'fascia',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/NovaLineCover/NovaLineCover_1.png',
    ],
    highlightDetails: {
      features: ['Compatible with a broad range of LYSAGHT® Guttering products.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours', 'Covers traditional timber fascia, subsequently reducing painting and maintenance'],
      productInfo:
        'NOVALINE® Fascia Cover can be used as a quick fix over existing warped, discoloured, or peeling timber fascia. This low maintenance fascia cover may be simply screw fixed to the existing timber fascia board.',
      specifications: {
        'Nominal  Height': '175mm',
        'Nominal Bottom Width': '35mm',
        'suitable for': 'Fascia'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/NovaLineCover_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure"
  },

  {
    id: 'lysaght-sheerline',
    title: 'Lysaght Sheerline',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/SheerLine/SheerLine_1.png',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours'],
      productInfo:
        'A square-fronted gutter offering a neat, streamlined appearance, SHEERLINE® guttering is readily used on patio, carport and shed structures, but is equally at home on residential homes and is suitable for use with both steel and tile roofs.',
      specifications: {
        'Nominal Front Height': '141mm',
        'Nominal Width': '124mm',
        'Nominal Back Height': '81mm',
        'Slotting': 'Slotted or unslotted',
        'suitable for': 'guttering.'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/SheerLine_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure"
  },

  {
    id: 'lysaght-trimline',
    title: 'Lysaght Trimline',
    type: 'guttering',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/TrimLine/TrimLine_1.png',
    ],
    highlightDetails: {
      features: ['Complete range of accessories available including brackets and stop ends.', 'Manufactured from aluminium/zinc/magnesium alloy-coated ZINCALUME® and COLORBOND® steel, featuring Activate® technology for improved corrosion resistance. COLORBOND® steel is available in a range of finishes and colours'],
      productInfo:
        'A square-fronted gutter offering a neat, streamlined appearance, TRIMLINE® guttering is readily used on patio, carport and shed structures, but is equally at home on residential homes and is suitable for use with both steel and tile roofs.',
      specifications: {
        'Nominal Front Height': '117mm',
        'Nominal Width': '124mm',
        'Nominal Back Height': '73mm',
        'Slotting': 'Slotted or unslotted',
        'suitable for': 'guttering.'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/TrimLine_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-rainwater-solutions-new-south-wales-brochure"
  },


  // Roofing
  {
    id: 'lysaght-custom-orb',
    title: 'Lysaght Custom Orb',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/CustomOrb/CustomOrb_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/CustomOrb/CustomOrb_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/CustomOrb/CustomOrb_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/CustomOrb/CustomOrb_4.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/CustomOrb/CustomOrb_5.jpg',
    ],
    highlightDetails: {
      features: ['Ideal for both roofing and walling.', 'efficient installation.', 'Strong, easy to handle, and long-lasting.', 'Classic corrugated design for any architectural style.'],
      productInfo:
        'Delivering a pleasingly textured visual with its uniform ‘ripple’, CUSTOM ORB® is the famous and original LYSAGHT® corrugated profile which others can only imitate. A lightweight and economical profile, CUSTOM ORB ® cladding offers the versatility of being laid flat or sprung curved and is equally at ease in both traditional and contemporary architecture.',
      specifications: {
        'Nominal Cover Width': '762mm',
        'Nominal Rib Height': '16mm',
        'Base Metal Thickness': '0.60 or 0.80mm',
        'Roof Slope': '5°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [
      {
        nametop: 'Classic Cream',
        hextop: '#E9DCB8',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Manor Red',
        hextop: '#5E1D0E',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Monument',
        hextop: '#2C2A29',
        nameunder: 'Surfmist',
        hexunder: '#F1F0E6',
      },
      {
        nametop: 'Paperbark',
        hextop: '#CABEAA',
        nameunder: 'Paperbark gloss',
        hexunder: '#CABEAA',
      },
      {
        nametop: 'Surfmist',
        hextop: '#F1F0E6',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },
      {
        nametop: 'Gully',
        hextop: '#7E7368',
        nameunder: 'Paperbark gloss',
        hexunder: '#CABEAA',
      },
      {
        nametop: 'Monument',
        hextop: '#2C2A29',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Monument',
        hextop: '#2C2A29',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },
      {
        nametop: 'Surfmist',
        hextop: '#F1F0E6',
        nameunder: 'Surfmist',
        hexunder: '#F1F0E6',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#4E4B45',
        nameunder: 'Paperbark gloss',
        hexunder: '#CABEAA',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#4E4B45',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/CustomOrb_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/custom-orb-and-custom-blue-orb-brochure"
  },
  {
    id: 'lysaght-flatdek',
    title: 'Lysaght Flatdek',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Flatdek/Flatdek_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Flatdek/Flatdek_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Flatdek/Flatdek_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Flatdek/Flatdek_4.jpg',
    ],
    highlightDetails: {
      features: ['Durable and lightweight', 'Low-maintenance', 'Perfect for outdoor and indoor applications'],
      productInfo:
        'Lysaght Flatdek is an advanced roofing and walling solution that combines durability with a sleek modern look. It is ideal for applications requiring both strength and aesthetic appeal.',
      specifications: {
        'Nominal Cover Width': '250mm',
        'Nominal Rib Height': '45mm',
        'Base Metal Thickness': '0.42mm',
        'Minimum Roof Slope': '1.3° to 2°',
        'Suitable For': 'Roofing',
      },
    },
    doubleside: [
      {
        nametop: 'Classic Cream',
        hextop: '#E9DCB8',
        nameunder: 'Classic Cream',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Manor Red',
        hextop: '#7A2F34',
        nameunder: 'Classic Cream',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Monument',
        hextop: '#4A4B4D',
        nameunder: 'Surfmist',
        hexunder: '#E4E2D5',
      },
      {
        nametop: 'Paperbark',
        hextop: '#CABFA4',
        nameunder: 'Paperbark',
        hexunder: '#CABFA4',
      },
      {
        nametop: 'Gully',
        hextop: '#73695A',
        nameunder: 'Paperbark',
        hexunder: '#CABFA4',
      },
      {
        nametop: 'Monument',
        hextop: '#4A4B4D',
        nameunder: 'Classic Cream',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Monument',
        hextop: '#4A4B4D',
        nameunder: 'Thredbo White',
        hexunder: '#F5EFE3',
      },
      {
        nametop: 'Surfmist',
        hextop: '#E4E2D5',
        nameunder: 'Surfmist',
        hexunder: '#E4E2D5',
      },
      {
        nametop: 'Surfmist',
        hextop: '#E4E2D5',
        nameunder: 'Thredbo White',
        hexunder: '#F5EFE3',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#464543',
        nameunder: 'Paperbark',
        hexunder: '#CABFA4',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#464543',
        nameunder: 'Classic Cream',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#464543',
        nameunder: 'Thredbo White',
        hexunder: '#F5EFE3',
      },
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Flatdek_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/flatdek-design-and-installation-guide"
  },
  {
    id: 'lysaght-trimdek',
    title: 'Lysaght Trimdek',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_4.jpg',
    ],
    highlightDetails: {
      features: ['Versatile Application: Ideal for both roofing and walling.', 'Wide Cover Width: 762mm for faster, more efficient installation.', 'Modern Design: Sleek trapezoidal profile perfect for contemporary architecture.', 'Durable and Lightweight: High strength with easy handling and installation.', 'Low Maintenance: Resistant to weathering and corrosion.', 'Efficient Water Drainage: Performs well on roofs with slopes as low as 2°.', 'Trimdek® is the perfect blend of functionality, style, and reliability.'],
      productInfo:
        'Trimdek® is a versatile roofing and walling profile known for its strength, durability, and modern aesthetic appeal. Manufactured using high-quality steel, Trimdek® combines functionality and design, making it an ideal choice for a wide range of applications, including residential, commercial, and industrial structures.',
      specifications: {
        'Nominal Cover Width': '762mm',
        'Nominal Rib Height': '29mm',
        'Base Metal Thickness': '0.42 or 0.48mm',
        'Minimum Roof Slope': '2°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Trimdek_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-trimdek-brochure"
  },
  {
    id: 'lysaght-kliplok700',
    title: 'Lysaght Kliplok 700',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700/Kliplok700_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700/Kliplok700_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700/Kliplok700_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700/Kliplok700_4.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700/Kliplok700_5.jpg',
    ],
    highlightDetails: {
      features: ['Utilizes a clip-fixed installation method, eliminating the need for exposed fasteners and ensuring superior watertightness.', 'Features bold ribs rising from wide, fluted pans, creating a distinctive linear visual suitable for both modern and traditional designs', 'Manufactured from high-tensile steel, providing excellent spanning capacity and resistance to harsh environmental conditions.'],
      productInfo:
        'An advanced profile featuring fluting across the width of the pan',
      specifications: {
        'Nominal Cover Width': '700mm',
        'Nominal Rib Height': '43mm',
        'Base Metal Thickness': '0.42 or 0.48mm',
        'Roof Slope': '1°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Kliplok700_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-kliplok-700-hi-strength-brochure"
  },
  {
    id: 'lysaght-kliplok-700-hl',
    title: 'Lysaght Kliplok 700 HL',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700HL/Kliplok700HL_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700HL/Kliplok700HL_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700HL/Kliplok700HL_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700HL/Kliplok700HL_4.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Kliplok700HL/Kliplok700HL_5.jpg',
    ],
    highlightDetails: {
      features: ['Utilizes a clip-fixed installation method, eliminating the need for exposed fasteners and ensuring superior watertightness.', 'Features bold ribs rising from wide, fluted pans, creating a distinctive linear visual suitable for both modern and traditional designs', 'Manufactured from high-tensile steel, providing excellent spanning capacity and resistance to harsh environmental conditions.'],
      productInfo:
        'An advanced profile featuring fluting across the width of the pan',
      specifications: {
        'Nominal Cover Width': '700mm',
        'Nominal Rib Height': '43mm',
        'Base Metal Thickness': '0.42 or 0.48mm',
        'Roof Slope': '1°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Kliplok700HL_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-kliplok-700-hi-strength-brochure"
  },
  {
    id: 'lysaght-spandek',
    title: 'Lysaght Spandek',
    type: 'roofing',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Spandek/Spandek_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Spandek/Spandek_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Spandek/Spandek_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Spandek/Spandek_4.jpg',
    ],
    highlightDetails: {
      features: ['Enhancing the visual appeal of both residential and commercial structures.', 'SPANDEK® combines strength with lightness and rigidity, offering excellent durability and impact resistance.', 'Suitable for both roofing and walling, making it a flexible choice for various architectural designs.', 'With a nominal cover width of 700mm and the ability to be used on roof slopes as low as 2°'],
      productInfo:
        'The contemporary-looking, square-corrugated profile of SPANDEK® is ideal where a stronger, striking and defined corrugated roofing or walling is required. Combining strength with lightness and rigidity, this popular cladding delivers durability, impact-resistance and economy with richly textured good looks.',
      specifications: {
        'Nominal Cover Width': '700mm',
        'Nominal Rib Height': '24mm',
        'Base Metal Thickness': '0.42 or 0.48mm',
        'Minimum Roof Slope': '2°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [
      {
        nametop: 'Classic Cream',
        hextop: '#E9DCB8',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Manor Red',
        hextop: '#5E1D0E',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },

      {
        nametop: 'Paperbark',
        hextop: '#CABEAA',
        nameunder: 'Paperbark gloss',
        hexunder: '#CABEAA',
      },
      {
        nametop: 'Surfmist',
        hextop: '#F1F0E6',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },

      {
        nametop: 'Monument',
        hextop: '#2C2A29',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#4E4B45',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Spandek_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/lysaght-spandek-design-and-installation-guide"
  },

  //WallCladding
  {
    id: 'lysaght-mini-orb',
    title: 'Lysaght Mini Orb',
    type: 'walling',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/MiniOrb/MiniOrb_1.png',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/41181.jpg?itok=s0OA48tw',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/28544.jpg?itok=0NXndJlZ',
    ],
    highlightDetails: {
      features: ['Ideal for both roofing and walling.', 'efficient installation.', 'Strong, easy to handle, and long-lasting.', 'Classic corrugated design for any architectural style.'],
      productInfo:
        'Its subtle mini corrugations make MINI ORB® a popular accent or feature, contrasting against other walling products & materials. MINI ORB® is suitable for both flat and curved installations and is suitable for interior and exterior applications. Its trademark corrugations can be installed either vertically or horizontally.',
      specifications: {
        'Nominal Cover Width': '820mm',
        'Nominal Rib Height': '6mm',
        'Base Metal Thickness': '0.42mm ',
        'Roof Slope': '2°',
        'Suitable For': 'Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/MiniOrb_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/walling-solutions"
  },
  {
    id: 'lysaght-trimwall',
    title: 'Lysaght Trimwall',
    model: '',
    type: 'walling',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_1.png',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_2.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_3.jpg',
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/Trimdek/Trimdek_4.jpg',
    ],
    highlightDetails: {
      features: [
        'Versatile Application: Ideal for walling.',
        'Wide Cover Width: 762mm for more efficient installation.',
        'Modern Design: Sleek trapezoidal profile perfect for contemporary architecture.',
        'Durable and Lightweight: High strength with easy handling and installation.',
        'Low Maintenance: Resistant to weathering and corrosion.',
        'Efficient Water Drainage: Performs well on roofs with slopes as low as 2°.',
        'Trimdek® is the perfect blend of functionality, style, and reliability for any project.'
      ],
      productInfo:
        'Trimwall® is a versatile roofing and walling profile known for its strength, durability, and modern aesthetic appeal. Manufactured using high-quality steel, Trimdek® combines functionality and design, making it an ideal choice for a wide range of applications, including residential, commercial, and industrial structures.',
      specifications: {
        'Nominal Cover Width': '762mm',
        'Nominal Rib Height': '28mm',
        'Base Metal Thickness': '0.42 or 0.48mm',
        'Suitable For': 'Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [
      {
        nametop: 'Classic Cream',
        hextop: '#E9DCB8',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
      {
        nametop: 'Manor Red',
        hextop: '#5E1D0E',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },

      {
        nametop: 'Paperbark',
        hextop: '#CABEAA',
        nameunder: 'Paperbark gloss',
        hexunder: '#CABEAA',
      },
      {
        nametop: 'Surfmist',
        hextop: '#F1F0E6',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },

      {
        nametop: 'Monument',
        hextop: '#2C2A29',
        nameunder: 'Thredbo White gloss',
        hexunder: '#FFFFFF',
      },
      {
        nametop: 'Woodland Grey',
        hextop: '#4E4B45',
        nameunder: 'Classic Cream gloss',
        hexunder: '#E9DCB8',
      },
    ],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/Trimwall_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/walling-solutions"
  },
  {
    id: 'lysaght-panelrib',
    title: 'Lysaght PanelRib',
    type: 'walling',
    model: '',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PanelRib/PanelRib_1.png',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/46986.jpg?itok=TOW1LBGk',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/46984.jpg?itok=5KVSvOPA',
    ],
    highlightDetails: {
      features: [
        'Durable and lightweight',
        'Low-maintenance',
        'Perfect for outdoor and indoor applications'
      ],
      productInfo: 'Lysaght PanelRib is an advanced walling solution that combines durability with a sleek modern look. It is ideal for applications requiring both strength and aesthetic appeal.',
      specifications: {
        'Nominal Cover Width': '250mm',
        'Nominal Rib Height': '45mm',
        'Base Metal Thickness': '0.42mm',
        'Minimum Roof Slope': '1.3° to 2°',
        'Suitable For': 'Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/walling-solutions",
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/MultiClad_accessories.pdf"
  },
  {
    id: 'lysaght-multi-clad',
    title: 'Lysaght MultiClad',
    model: '',
    type: 'walling',
    carouselImages: [
      'https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/MultiClad/MultiClad_1.png',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/46986.jpg?itok=TOW1LBGk',
      'https://lysaght.com/sites/default/files/styles/max_1300x1300/public/2022-06/46984.jpg?itok=5KVSvOPA',
    ],
    highlightDetails: {
      features: [
        'An efficient walling profile thanks to its lightness and broad cover width, MULTICLAD® is an ideal wall cladding for sheds & garages.',
        'The profile features raised rib sections of two varying heights across the sheet width, providing an attractive appearance.',
        'MULTICLAD® is an ideal wall cladding profile option when an inexpensive, lightweight and quick-to-install cladding is required.',
      ],
      productInfo:
        'MULTICLAD® is an efficient walling profile thanks to its lightness and broad cover width, making it an ideal wall cladding for sheds & garages. The profile features raised rib sections of two varying heights across the sheet width, providing an attractive appearance. MULTICLAD® is an ideal wall cladding profile option when an inexpensive, lightweight and quick-to-install cladding is required.',
      specifications: {
        'Nominal Cover Width': '840mm',
        'Nominal Rib Height': '12mm',
        'Base Metal Thickness': ' 0.35 or 0.42mm',
        'Suitable For': 'Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    accessoriesLink: "https://goomorproductimage.s3.ap-southeast-2.amazonaws.com/Lysaght/PDF/MultiClad_accessories.pdf",
    learnMoreLink: "https://cdn.dcs.lysaght.com/download/walling-solutions"
  }
];

