// src/data/productData.js
export const products = [
  {
    id: 'metroll-fascia-cover',
    title: 'Metroll Fascia Cover',
    type: 'fascia',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/FasciaCover/FasciaCover.png',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo: 'Metroll Fascia Cover is designed for use in conjunction with patio, verandah, carport and garage applications.',
      specifications: {
        'Nominal Height': '179mm',
        'Nominal Top Width': '16.5mm',
        'Nominal Bottom Width': '37mm',
        'Suitable For': 'Fascia',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
    
  },
  {
    id: 'half-round-gutter-150',
    title: 'Metroll Half Round Gutter 150',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/HRGutter150/HRGutter150_1.png',
      '/goomorproductimage/Metroll/HRGutter150/HRGutter150_2.jpg',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo: 'HR Gutter is designed for use in conjunction with patio, verandah, carport and garage applications.',
      specifications: {
        'Nominal Front Height': '89mm',
        'Nominal Width': '150mm',
        'Nominal Back Height': '85mm',
        suitableFor: 'Guttering',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },

  // Repeat for other products
  {
    id: 'metroll-downpipes-round',
    title: 'Metroll Downpipes Round',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/DownPipesRound/DownPipesRound_1.png',
    ],
    highlightDetails: {
      features: [
        'Manufactured from premium COLORBOND® steel or ZINCALUME® steel, ensuring longevity and resistance to Australia diverse climatic conditions.',
        'Available in various sizes to accommodate different building requirements, with the 90mm and 100mm round profile being a common choice.',
        'A full range of accessories is available, including brackets/astragals, pops/nozzles, offsets, elbows, and shoes, facilitating seamless integration into any drainage system.',
      ],
      productInfo:
        'Metroll® offers a range of high-quality downpipes crafted from durable COLORBOND® steel and ZINCALUME® steel. Among these, the round profile downpipes are particularly notable for their efficiency and aesthetic appeal.',
      specifications: {
        'Profile style': 'Round',
        'Nominal Width': '90mm and 100mm',
        suitableFor: 'Guttering',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },

  {
    id: 'metroll-downpipes-square',
    title: 'Metroll Downpipes Square',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/DownPipesSquare/DownPipesSquare_100X50.png',
      '/goomorproductimage/Metroll/DownPipesSquare/DownPipesSquare_100X75.png',
    ],
    highlightDetails: {
      features: [
        'Manufactured from premium COLORBOND® steel or ZINCALUME® steel, ensuring longevity and resistance to Australia diverse climatic conditions.',
        'Available in various dimensions to accommodate different building requirements, with the 100mmx50mm and 100mmx75mm square profile being a common choice.',
        'A full range of accessories is available, including brackets/astragals, pops/nozzles, offsets, elbows, and shoes, facilitating seamless integration into any drainage system.',
      ],
      productInfo:
        'Metroll® offers a range of high-quality downpipes crafted from durable COLORBOND® steel and ZINCALUME® steel. Among these, the square profile downpipes are particularly notable for their clean lines and robust design, making them ideal for modern and industrial architectural styles.',
      specifications: {
        'Profile style': 'Square',
        'Dimensions': '100mm x 50mm OR 100mm x 75mm',
        suitableFor: 'Guttering',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },

  {
    id: 'metroll-fascia-gutter',
    title: 'Metroll Fascia Gutter',
    type: 'fascia',
    model: '',  
    carouselImages: [
      '/goomorproductimage/Metroll/MetroFasciaGutter/MetroFasciaGutter_1.png',
      '/goomorproductimage/Metroll/MetroFasciaGutter/MetroFasciaGutter_2.jpg',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo:
        'Metroll Fascia Gutter is designed for use in conjunction with patio, verandah, carport and garage applications. The wide return fold on the back of the profile allows it to be fixed to the roof sheeting.',
      specifications: {
        'Nominal Front Height': '136mm',
        'Nominal Width': '125mm',
        'Nominal Back Height': '83mm',
        'Nominal Top Width': '25mm',
        suitableFor: 'Fascia',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },

  {
    id: 'metroll-skyline-gutter',
    title: 'Metroll Skyline Gutter',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/SkyLineGutter/SkyLineGutter_1.png',
      '/goomorproductimage/Metroll/SkyLineGutter/SkyLineGutter_2.jpg',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo:
        'The Skyline Gutter is an elegant, modern profile well suited to high-end architectural applications.',
      specifications: {
        'Nominal Front Height': '89mm',
        'Nominal Width': '137mm',
        'Nominal Back Height': '75mm',
        suitableFor: 'Guttering',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },
  {
    id: 'metroll-metroline-fascia-gutter',
    title: 'Metroll Metro Line Fascia Gutter',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/MetroLineFasciaGutter/MetroLineFasciaGutter_1.png',
      '/goomorproductimage/Metroll/MetroLineFasciaGutter/MetroLineFasciaGutter_2.png',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo:
        'Metroline Fascia Gutter is designed for use in conjunction with patio, verandah, carport and garage applications. The wide return fold on the back of the profile allows it to be fixed to the roof sheeting.',
      specifications: {
        'Nominal Front Height': '113mm',
        'Nominal Width': '114mm',
        'Nominal Back Height': '64mm',
        'suitable for': 'Fascia'
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' }
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },
  {
    id: 'metroll-quad',
    title: 'Metroll METROLL QUAD HI-FRONT',
    type: 'guttering',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/Quad/HFQuadGutter150_1.png',
      '/goomorproductimage/Metroll/Quad/HFQuadGutter150_2.jpg',
    ],
    highlightDetails: {
      features: ['Wide range of uses', 'COLORBOND® steel colour range', 'Easy to install'],
      productInfo: 'One of the most popular profiles, the high front provides for a great aesthetic finish to any project.',
      specifications: {
        'Nominal Front Height': '90, 94, 98, 99mm',
        'Nominal Width': '115, 107, 130, 160mm',
        'Nominal Back Height': '61, 68, 68, 71mm',
        'Suitable For': 'Guttering',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_rainwater_goods23.pdf'],
  },
  // roofing
  {
    id: 'corodek',
    title: 'Metroll CORODEK®',
    type: 'roofing',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/CoroDek/CoroDek_1.jpg',
      '/goomorproductimage/Metroll/CoroDek/CoroDek_2.png',
      '/goomorproductimage/Metroll/CoroDek/CoroDek_3.jpg',
    ],
    highlightDetails: {
      features: [
        'Versatile Application: Ideal for both roofing and walling.',
        'High tensile steel',
        'Long lengths',
        'Elegant, traditional appearance',
      ],
      productInfo: 'A traditional roofing profile, Corodek® is multipurpose roofing and wall sheeting that is the preferred choice for domestic applications.',
      specifications: {
        'Nominal Cover Width': '762mm',
        'Nominal Height': '16mm',
        'Nominal Rib Spacing': '130mm',
        'Base Metal Thickness': '0.42 - 0.48 - 0.60mm',
        'Minimum Roof Slope': '2°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_cyclonic_design_manual2.pdf'],
    accessoriesLink: 'https://www.metroll.com.au/wp-content/uploads/metroll_corodek_21r.pdf',
  },
  {
    id: 'metroll-metlok-700-hp',
    title: 'Metroll Metlok® 700 HP – Concealed Fix Roofing & Walling',
    type: 'roofing',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/MetLok700HP/MetLok700HP_1.jpg',
      '/goomorproductimage/Metroll/MetLok700HP/Metlok700HP_2.png',
      '/goomorproductimage/Metroll/MetLok700HP/Metlok700HP_3.png',
    ],
    highlightDetails: {
      features: [
        'Optimised underclip for speedy installation.',
        'Ideal for long runs',
        'Concealed fix',
      ],
      productInfo: 'Metlok® HP (High Performance) is a concealed fix roof system designed for long run roofing applications. It can also be used for walling. Whilst similar to Metlok 700®, Metlok® HP features an underclip, not an overclip. The Metlok® HP underclip does not require installation over the top of the sheets which allows for bulk clip installation to the purlins. This makes Metlok® HP installation speedier and easier.',
      specifications: {
        'Nominal Cover Width': '695mm',
        'Nominal Height': '40mm',
        'Base Metal Thickness': '0.42 OR 0.48mm',
        'Minimum Roof Slope': '1°',
        'Suitable For': 'Roofing',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['/goomorproductimage/Metroll/MetLok700HP/PDF/metroll_metlokHP_Nov24.pdf'],
  },
  {
    id: 'metroll-metro-span',
    title: 'Metroll Metrospan® – High Strength Square Profile',
    carouselImages: [
      '/goomorproductimage/Metroll/MetroSpan/MetroSpan_1.jpg',
      '/goomorproductimage/Metroll/MetroSpan/MetroSpan_2.png',
      '/goomorproductimage/Metroll/MetroSpan/MetroSpan_3.png',
      // (Add other images here)
    ],
    highlightDetails: {
      features: [
        'Versatile Application: Ideal for both roofing and walling.',
        'High strength',
        'Impact resistant',
        'Long spanning capability',
      ],
      productInfo: 'Metrospan® is ideal roofing and wall cladding for commercial and industrial buildings, roofing for new homes, home extensions, carports, garages, patios, fencing, fascia, and façade work.',
      specifications: {
        'Nominal Cover Width': '700mm',
        'Nominal Height': '24mm',
        'Base Metal Thickness': '0.42 OR 0.48mm',
        'Minimum Roof Slope': '1°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_cyclonic_design_manual2.pdf'],
    accessoriesLink: 'https://www.metroll.com.au/wp-content/uploads/metroll_metrospan_apr24.pdf',
  },

  {
    id: 'metroll-trimclad',
    title: 'Metroll TRIMCLAD®',
    type: 'roofing',
    model: '',
    carouselImages: [
      '/goomorproductimage/Metroll/TrimClad/TrimClad_1.jpg',
      '/goomorproductimage/Metroll/TrimClad/TrimClad_2.png',
      '/goomorproductimage/Metroll/TrimClad/TrimClad_3.png',
      '/goomorproductimage/Metroll/TrimClad/TrimClad_4.jpg',

    ],
    highlightDetails: {
      features: [
        'Versatile Application: Ideal for both roofing and walling.',
        'Requiring only a minimum pitch of 2 degrees',
        'Trimclad® can be custom cut to specified lengths and comes in the range of COLORBOND® steel colours.',
      ],
      productInfo: 'Requiring only a minimum pitch of 2 degrees Trimclad® roofing and walling is a preferred choice for commercial and industrial uses.',
      specifications: {
        'Nominal Rib Width': '60mm',
        'Nominal Height': '29mm',
        'Nominal Rib Spacing': '130mm',
        'Base Metal Thickness': '0.42 or 0.48mm (Only available for roofing)',
        'Minimum Roof Slope': '2°',
        'Suitable For': 'Roofing, Walling',
      },
    },
    colors: [
      { name: 'Dover White', hex: '#F9FBF1' },
      { name: 'Surfmist', hex: '#E4E2D5' },
      { name: 'Evening Haze', hex: '#C5C2AA' },
      { name: 'Classic Cream', hex: '#E9DCB8' },
      { name: 'Paperbark', hex: '#CABFA4' },
      { name: 'Dune', hex: '#B1ADA3' },
      { name: 'Southerly', hex: '#D2D1CB' },
      { name: 'Shale Grey', hex: '#BDBFBA' },
      { name: 'Bluegum', hex: '#969799' },
      { name: 'Windspray', hex: '#888B8A' },
      { name: 'Gully', hex: '#857E73' },
      { name: 'Jasper', hex: '#6C6153' },
      { name: 'Wallaby', hex: '#7F7C78' },
      { name: 'Basalt', hex: '#6D6C6E' },
      { name: 'Woodland Grey', hex: '#4B4C46' },
      { name: 'Monument', hex: '#323233' },
      { name: 'Night Sky', hex: '#000000' },
      { name: 'Ironstone', hex: '#3E434C' },
      { name: 'Deep Ocean', hex: '#364152' },
      { name: 'Cottage Green', hex: '#304C3C' },
      { name: 'Pale Eucalypt', hex: '#7C846A' },
      { name: 'Manor Red', hex: '#5E1D0E' },
    ],
    doubleside: [],
    finishes: [],
    learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_trimclad_24.pdf'],
    accessoriesLink: 'https://www.metroll.com.au/wp-content/uploads/metroll_trimclad_cyc_Oct21.pdf',
  },
//  WallCladding
{
  id: 'metroll-metrib',
  title: 'Metroll Metrib® Low Profile Cladding',
  type: 'walling',
  model: '',
  carouselImages: [
    '/goomorproductimage/Metroll/MetRib/MetRib_1.jpg',
    '/goomorproductimage/Metroll/MetRib/MetRib_2.png',
    '/goomorproductimage/Metroll/MetRib/MetRib_3.jpg',
  ],
  highlightDetails: {
    features: [
      'Install on straight or curved surfaces',
      'Low rib height',
      'Install horizontally or vertically',
      'Easy to install',
      'Wide range of uses',
      'Can be used in place of fibre cement or plasterboard',
    ],
    productInfo: 'Metrib® can be used on interior or exterior walls, on straight or curved surfaces and with the flutes installed in a horizontal or vertical direction. Designed as a low rib, flute profile, Metrib® is suitable for many applications where flat sheets cannot be used, including sheds, portable buildings, bus shelters, internal wall linings, soffits and the inner curve of arches.',
    specifications: {
      'Nominal Cover Width': '850mm',
      'Nominal Height': '4mm',
      'Base Metal Thickness': '0.42 & 0.48mm',
      'Suitable For': 'Walling',
    },
  },
  colors: [
    { name: 'Dover White', hex: '#F9FBF1' },
    { name: 'Surfmist', hex: '#E4E2D5' },
    { name: 'Evening Haze', hex: '#C5C2AA' },
    { name: 'Classic Cream', hex: '#E9DCB8' },
    { name: 'Paperbark', hex: '#CABFA4' },
    { name: 'Dune', hex: '#B1ADA3' },
    { name: 'Southerly', hex: '#D2D1CB' },
    { name: 'Shale Grey', hex: '#BDBFBA' },
    { name: 'Bluegum', hex: '#969799' },
    { name: 'Windspray', hex: '#888B8A' },
    { name: 'Gully', hex: '#857E73' },
    { name: 'Jasper', hex: '#6C6153' },
    { name: 'Wallaby', hex: '#7F7C78' },
    { name: 'Basalt', hex: '#6D6C6E' },
    { name: 'Woodland Grey', hex: '#4B4C46' },
    { name: 'Monument', hex: '#323233' },
    { name: 'Night Sky', hex: '#000000' },
    { name: 'Ironstone', hex: '#3E434C' },
    { name: 'Deep Ocean', hex: '#364152' },
    { name: 'Cottage Green', hex: '#304C3C' },
    { name: 'Pale Eucalypt', hex: '#7C846A' },
    { name: 'Manor Red', hex: '#5E1D0E' },
  ],
  doubleside: [],
  finishes: [],
  learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_metrib_24.pdf'],
  accessoriesLink: '',
},
{
  id: 'metroll-metroclad',
  title: 'Metroll MetroClad® – Wide Coverage Steel Walling',
  type: 'walling',
  model: '',
  carouselImages: [
    '/goomorproductimage/Metroll/MetroClad/MetroClad_1.jpg',
    '/goomorproductimage/Metroll/MetroClad/MetroClad_2.png',
    '/goomorproductimage/Metroll/MetroClad/MetroClad_3.png',
  ],
  highlightDetails: {
    features: [
      'Versatile & durable',
      'Low rib height',
      'Ideal for commercial, rural and residential applications',
      'Easy to install',
    ],
    productInfo: 'MetroClad® is a designer cladding profile suited to both exterior and interior – it can be applied straight or curved.',
    specifications: {
      'Nominal Cover Width': '864mm',
      'Nominal Height': '11mm',
      'Base Metal Thickness': '0.42mm',
      'Suitable For': 'Walling',
    },
  },
  colors: [
    { name: 'Dover White', hex: '#F9FBF1' },
    { name: 'Surfmist', hex: '#E4E2D5' },
    { name: 'Evening Haze', hex: '#C5C2AA' },
    { name: 'Classic Cream', hex: '#E9DCB8' },
    { name: 'Paperbark', hex: '#CABFA4' },
    { name: 'Dune', hex: '#B1ADA3' },
    { name: 'Southerly', hex: '#D2D1CB' },
    { name: 'Shale Grey', hex: '#BDBFBA' },
    { name: 'Bluegum', hex: '#969799' },
    { name: 'Windspray', hex: '#888B8A' },
    { name: 'Gully', hex: '#857E73' },
    { name: 'Jasper', hex: '#6C6153' },
    { name: 'Wallaby', hex: '#7F7C78' },
    { name: 'Basalt', hex: '#6D6C6E' },
    { name: 'Woodland Grey', hex: '#4B4C46' },
    { name: 'Monument', hex: '#323233' },
    { name: 'Night Sky', hex: '#000000' },
    { name: 'Ironstone', hex: '#3E434C' },
    { name: 'Deep Ocean', hex: '#364152' },
    { name: 'Cottage Green', hex: '#304C3C' },
    { name: 'Pale Eucalypt', hex: '#7C846A' },
    { name: 'Manor Red', hex: '#5E1D0E' },
  ],
  doubleside: [],
  finishes: [],
  learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_metroclad_apr24.pdf'],
  accessoriesLink: '',
},
{
  id: 'metroll-mini-corodek',
  title: 'Metroll Mini Corodek® – Designer Cladding',
  type: 'walling',
  model: '',
  carouselImages: [
    '/goomorproductimage/Metroll/MiniCoroDek/MiniCoroDek_1.jpg',
    '/goomorproductimage/Metroll/MiniCoroDek/MiniCoroDek_2.jpg',
    '/goomorproductimage/Metroll/MiniCoroDek/MiniCoroDek_3.png',
  ],
  highlightDetails: {
    features: [
      'Wide range of uses',
      'Install horizontally or vertically',
      'COLORBOND® steel colour range',
      'Easy to install',
    ],
    productInfo: 'Mini Corodek® is a designer cladding profile suited to both exterior and interior – it can be applied straight or curved.',
    specifications: {
      'Nominal Cover Width': '825mm',
      'Nominal Height': '6mm',
      'Base Metal Thickness': '0.42 & 0.48mm',
      'Suitable For': 'Walling',
    },
  },
  colors: [
    { name: 'Dover White', hex: '#F9FBF1' },
    { name: 'Surfmist', hex: '#E4E2D5' },
    { name: 'Evening Haze', hex: '#C5C2AA' },
    { name: 'Classic Cream', hex: '#E9DCB8' },
    { name: 'Paperbark', hex: '#CABFA4' },
    { name: 'Dune', hex: '#B1ADA3' },
    { name: 'Southerly', hex: '#D2D1CB' },
    { name: 'Shale Grey', hex: '#BDBFBA' },
    { name: 'Bluegum', hex: '#969799' },
    { name: 'Windspray', hex: '#888B8A' },
    { name: 'Gully', hex: '#857E73' },
    { name: 'Jasper', hex: '#6C6153' },
    { name: 'Wallaby', hex: '#7F7C78' },
    { name: 'Basalt', hex: '#6D6C6E' },
    { name: 'Woodland Grey', hex: '#4B4C46' },
    { name: 'Monument', hex: '#323233' },
    { name: 'Night Sky', hex: '#000000' },
    { name: 'Ironstone', hex: '#3E434C' },
    { name: 'Deep Ocean', hex: '#364152' },
    { name: 'Cottage Green', hex: '#304C3C' },
    { name: 'Pale Eucalypt', hex: '#7C846A' },
    { name: 'Manor Red', hex: '#5E1D0E' },
  ],
  doubleside: [],
  finishes: [],
  learnMoreLinks: ['https://www.metroll.com.au/wp-content/uploads/metroll_mini_corodek_Apr23.pdf'],
  
},

];

